"""
Module:  html_renderer.py
Agent:   Memo Generation Agent
Purpose: Assembles all section HTML blocks into the final self-contained HTML file.
         Embeds CSS, Chart.js library, and all section content into a single file.
         The output HTML works offline with no external dependencies.
Inputs:  List of section HTML strings, CSS from styles.py.
Outputs: Complete HTML string for the investment memo.
"""

import logging
from pathlib import Path
from typing import Any

from agents.memo_generation.styles import get_base_css

logger = logging.getLogger(__name__)

# Path to Chart.js local file
CHARTJS_LOCAL_PATH = Path(__file__).parent / "assets" / "chart.umd.min.js"


def _load_chartjs_inline() -> str:
    """Load Chart.js from local file and return as inline script tag.

    Returns:
        HTML script tag with Chart.js source embedded inline.
    """
    try:
        if CHARTJS_LOCAL_PATH.exists():
            js_content = CHARTJS_LOCAL_PATH.read_text(encoding="utf-8")
            return f"<script>{js_content}</script>"
        else:
            logger.warning(f"Chart.js local file not found at {CHARTJS_LOCAL_PATH}, using CDN fallback")
            return '<script src="https://cdn.jsdelivr.net/npm/chart.js@4.4.4/dist/chart.umd.min.js"></script>'
    except Exception as e:
        logger.error(f"Failed to load Chart.js: {e}")
        return '<script src="https://cdn.jsdelivr.net/npm/chart.js@4.4.4/dist/chart.umd.min.js"></script>'


def _build_table_of_contents() -> str:
    """Build the Table of Contents navigation section.

    Returns:
        HTML string for the ToC.
    """
    sections = [
        ("1", "Executive Summary", "section-1"),
        ("2", "Company & Business Overview", "section-2"),
        ("3", "5-Year Financial Statements", "section-3"),
        ("4", "Financial Ratio Analysis", "section-4"),
        ("5", "Trend Analysis & Sudden Changes", "section-5"),
        ("6", "Fraud & Distress Detection", "section-6"),
        ("7", "Anomaly Detection Results", "section-7"),
        ("8", "Sector Benchmarking", "section-8"),
        ("9", "Earnings Quality Score", "section-9"),
        ("10", "Competitive Landscape", "section-10"),
        ("11", "Implied Valuation Analysis", "section-11"),
        ("12", "News Sentiment & Media", "section-12"),
        ("13", "Industry & Macro Context", "section-13"),
        ("14", "Risk Assessment", "section-14"),
        ("15", "Mitigation Recommendations", "section-15"),
        ("16", "Data Verification Report", "section-16"),
        ("17", "Appendix & Methodology", "section-17"),
    ]

    items = []
    for num, title, anchor in sections:
        items.append(f'<li><a href="#{anchor}"><span class="toc-num">{num}.</span>{title}</a></li>')

    return f"""
    <div class="toc">
        <div class="toc-title">📋 Table of Contents</div>
        <ul class="toc-list">
            {''.join(items)}
        </ul>
    </div>
    """


def assemble_html(
    company_name: str,
    ticker: str,
    cover_html: str,
    section_htmls: list[str],
    run_id: str = "",
) -> str:
    """Assemble the complete HTML document from all section blocks.

    Args:
        company_name: Company name for the <title> tag.
        ticker: Ticker symbol for the <title> tag.
        cover_html: HTML string for the cover page (Section 0).
        section_htmls: Ordered list of HTML strings for Sections 1-17.
        run_id: Run ID for metadata.

    Returns:
        Complete self-contained HTML string.
    """
    css = get_base_css()
    toc = _build_table_of_contents()
    chartjs_script = _load_chartjs_inline()

    # Combine all section HTML
    sections_combined = "\n".join(section_htmls)

    html = f"""<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="Investment Due Diligence Memorandum for {company_name} ({ticker}) — Generated by DeligenX Platform">
    <meta name="generator" content="DeligenX Memo Generation Agent">
    <meta name="run-id" content="{run_id}">
    <title>{company_name} ({ticker}) — Investment Due Diligence Memorandum | DeligenX</title>

    <!-- Chart.js (embedded inline for offline capability) -->
    {chartjs_script}

    <style>
{css}
    </style>
</head>
<body>

    <!-- ═══════════════════════════════════════════════════════════════ -->
    <!-- COVER PAGE                                                     -->
    <!-- ═══════════════════════════════════════════════════════════════ -->
    {cover_html}

    <!-- ═══════════════════════════════════════════════════════════════ -->
    <!-- MAIN REPORT CONTENT                                            -->
    <!-- ═══════════════════════════════════════════════════════════════ -->
    <div class="memo-container">

        {toc}

        <div class="divider-thick"></div>

        {sections_combined}

        <!-- ═══════════════════════════════════════════════════════════ -->
        <!-- FOOTER                                                     -->
        <!-- ═══════════════════════════════════════════════════════════ -->
        <div class="divider-thick"></div>
        <div style="text-align:center; padding: 32px 0; color: #94A3B8; font-size: 0.8rem;">
            <p style="margin:0;">
                <strong style="color: #1B2A4A;">DeligenX</strong> — AI-Powered Investment Due Diligence Platform
            </p>
            <p style="margin:4px 0 0 0;">
                This report was generated autonomously by DeligenX's 5-agent AI pipeline.
                All financial data is sourced from SEC EDGAR XBRL filings and verified against source documents.
            </p>
            <p style="margin:4px 0 0 0;">
                Run ID: <span style="font-family: 'JetBrains Mono', monospace;">{run_id}</span>
            </p>
            <p style="margin:12px 0 0 0; font-size: 0.7rem; letter-spacing: 1px; text-transform: uppercase;">
                Confidential — For Authorized Recipients Only
            </p>
        </div>

    </div><!-- /memo-container -->

</body>
</html>"""

    logger.info(
        f"HTML assembled: {len(html):,} characters, "
        f"{len(section_htmls)} sections + cover page"
    )

    return html
