"""
Module:  llm_narrator.py
Agent:   Memo Generation Agent
Purpose: LLM narrative generation wrapper for professional investment memo paragraphs.
         Uses Gemini 2.5 Pro (via LiteLLM + Vertex AI) for ALL narrative generation.
         NO financial numbers are generated by LLM — only professional text narratives.
Inputs:  Structured data dicts from data_collector, section context.
Outputs: Professional narrative text strings.
"""

import logging
import time
import re
from typing import Any

import litellm
from dotenv import load_dotenv

load_dotenv()

# Disable litellm's internal retries — we handle retries ourselves
litellm.num_retries = 0

logger = logging.getLogger(__name__)

# All memo generation uses Gemini 2.5 Pro for best quality
DEFAULT_MODEL = "vertex_ai/gemini-2.5-pro"


def _call_llm(system_prompt: str, user_prompt: str, max_retries: int = 3,
              temperature: float = 0.3) -> str:
    """Call LLM with retry logic and return the text response.

    Args:
        system_prompt: System-level instructions for the LLM.
        user_prompt: User-level prompt with data and instructions.
        max_retries: Maximum retry attempts on failure.
        temperature: LLM temperature (lower = more deterministic).

    Returns:
        The LLM's text response, or empty string on failure.
    """
    for attempt in range(max_retries):
        try:
            response = litellm.completion(
                model=DEFAULT_MODEL,
                messages=[
                    {"role": "system", "content": system_prompt},
                    {"role": "user", "content": user_prompt},
                ],
                temperature=temperature,
                max_tokens=4096,
                num_retries=0,
            )
            text = response.choices[0].message.content
            if text:
                logger.info(f"LLM call successful (attempt {attempt + 1}, "
                            f"tokens: {response.usage.total_tokens})")
                return text.strip()
            logger.warning(f"LLM returned empty response on attempt {attempt + 1}")
        except Exception as e:
            wait = 2 ** attempt + 1
            logger.warning(f"LLM call failed (attempt {attempt + 1}/{max_retries}): {e}. "
                           f"Retrying in {wait}s...")
            time.sleep(wait)

    logger.error(f"LLM call failed after {max_retries} attempts")
    return ""


# ══════════════════════════════════════════════════════════════════════
#                    SECTION-SPECIFIC NARRATORS
# ══════════════════════════════════════════════════════════════════════

SYSTEM_PROMPT_BASE = """You are an elite investment analyst at a top-tier institutional investment firm.
You write professional, objective, data-driven narratives for investment due diligence memorandums.

CRITICAL RULES:
1. NEVER invent, estimate, or hallucinate any financial numbers. You may ONLY reference numbers
   that are explicitly provided to you in the data below.
2. Write in a professional, third-person, institutional tone.
3. Be balanced — acknowledge both strengths and risks.
4. Use specific data points from the provided context to support every claim.
5. Do NOT use markdown formatting (no **, ##, etc.). Write plain HTML-ready text.
6. Write in complete, well-structured paragraphs (not bullet points).
7. Each paragraph should be 3-5 sentences long.
"""


def generate_executive_summary_narrative(data: dict) -> str:
    """Generate the 3-4 paragraph key findings narrative for the Executive Summary.

    Args:
        data: Dict containing qoe_summary, risk_assessment, market_intel, company info.

    Returns:
        HTML-formatted narrative string.
    """
    user_prompt = f"""
Write a 3-4 paragraph executive summary narrative for an Investment Due Diligence Memorandum.

COMPANY: {data.get('company_name', 'N/A')} ({data.get('ticker', 'N/A')})
INDUSTRY: {data.get('industry_name', 'N/A')}

KEY DATA POINTS:
- Earnings Quality Score: {data.get('qoe_score', 'N/A')}/100 ({data.get('qoe_label', 'N/A')})
- Composite Risk Score: {data.get('risk_score', 'N/A')}/100 (Level: {data.get('risk_level', 'N/A')})
- Investment Stance: {data.get('investment_stance', 'N/A')}
- Deal Breakers Triggered: {data.get('deal_breakers_triggered', 0)} of 8
- Competitive Position: {data.get('competitive_position', 'N/A')}
- Moat Width: {data.get('moat_width', 'N/A')}
- Current Price: ${data.get('current_price', 'N/A')}
- Market Cap: {data.get('market_cap_display', 'N/A')}

TOP STRENGTHS: {data.get('top_strengths', 'N/A')}
TOP CONCERNS: {data.get('top_concerns', 'N/A')}
KEY ADVANTAGES: {data.get('key_advantages', 'N/A')}
KEY VULNERABILITIES: {data.get('key_vulnerabilities', 'N/A')}

PARAGRAPH STRUCTURE:
1. Financial Health — Quality of Earnings assessment, key financial strengths/weaknesses
2. Competitive Position — Market standing, moat assessment, competitive advantages
3. Risk Profile — Overall risk level, deal breakers, key risk areas
4. Investment Conclusion — Synthesize the above into a clear investment thesis statement

Wrap each paragraph in <p> tags.
"""
    return _call_llm(SYSTEM_PROMPT_BASE, user_prompt)


def generate_company_overview_narrative(data: dict) -> str:
    """Generate the business description narrative from ChromaDB RAG context.

    Args:
        data: Dict containing company info and ChromaDB extracted text chunks.

    Returns:
        HTML-formatted narrative string.
    """
    user_prompt = f"""
Write a 3-4 paragraph business overview narrative for an Investment Due Diligence Memorandum.

COMPANY: {data.get('company_name', 'N/A')} ({data.get('ticker', 'N/A')})
INDUSTRY: {data.get('industry_name', 'N/A')} (SIC: {data.get('sic_code', 'N/A')})
EXCHANGE: {data.get('exchange', 'N/A')}
FISCAL YEAR END: {data.get('fiscal_year_end', 'N/A')}

SEC FILING CONTEXT (from 10-K Item 1 — Business Description):
{data.get('business_description_chunks', 'No filing context available.')}

MD&A CONTEXT (from 10-K Item 7):
{data.get('mda_chunks', 'No MD&A context available.')}

PARAGRAPH STRUCTURE:
1. Core Business — What the company does, its primary products/services, business model
2. Market Position — Key markets, geographic presence, competitive advantages
3. Recent Developments — Strategic initiatives, acquisitions, new products (from MD&A)

Wrap each paragraph in <p> tags. Only use information that is explicitly stated in the filing context above.
"""
    return _call_llm(SYSTEM_PROMPT_BASE, user_prompt)


def generate_ratio_analysis_narrative(data: dict) -> str:
    """Generate the ratio analysis narrative paragraph.

    Args:
        data: Dict with top ratios, trends, benchmark positions.

    Returns:
        HTML-formatted narrative string.
    """
    user_prompt = f"""
Write a 3-4 paragraph financial ratio analysis narrative for an Investment Due Diligence Memorandum.

COMPANY: {data.get('company_name', 'N/A')} ({data.get('ticker', 'N/A')})

KEY RATIOS (Latest Year):
{data.get('key_ratios_text', 'N/A')}

TREND ANALYSIS:
- Improving Trends: {data.get('improving_trends', 'None')}
- Declining Trends: {data.get('declining_trends', 'None')}
- Sudden Changes: {data.get('sudden_changes', 'None')}

SECTOR BENCHMARK POSITION:
{data.get('benchmark_text', 'N/A')}

PARAGRAPH STRUCTURE:
1. Profitability Assessment — Margins, returns on capital, and their trajectories
2. Financial Stability — Liquidity, leverage, and solvency ratios
3. Efficiency & Growth — Operational efficiency metrics and growth rates
4. Key Takeaways — The most significant findings from the ratio analysis

Wrap each paragraph in <p> tags.
"""
    return _call_llm(SYSTEM_PROMPT_BASE, user_prompt)


def generate_trend_narrative(data: dict) -> str:
    """Generate the trend analysis narrative.

    Args:
        data: Dict with trend details and sudden changes.

    Returns:
        HTML-formatted narrative string.
    """
    user_prompt = f"""
Write a 2-3 paragraph trend analysis narrative for an Investment Due Diligence Memorandum.

COMPANY: {data.get('company_name', 'N/A')}

TREND SUMMARY:
- Total Ratios Analyzed: {data.get('total_ratios', 'N/A')}
- Improving: {data.get('improving_count', 0)}
- Declining: {data.get('declining_count', 0)}
- Stable: {data.get('stable_count', 0)}
- Volatile: {data.get('volatile_count', 0)}

KEY IMPROVING TRENDS: {data.get('improving_details', 'None')}
KEY DECLINING TRENDS: {data.get('declining_details', 'None')}
SUDDEN CHANGES: {data.get('sudden_changes_details', 'None')}

Focus on the investment-relevant implications of these trends. What do they tell us about the
company's trajectory? Are there red flags or positive signals?

Wrap each paragraph in <p> tags.
"""
    return _call_llm(SYSTEM_PROMPT_BASE, user_prompt)


def generate_competitive_landscape_narrative(data: dict) -> str:
    """Generate the competitive landscape narrative.

    Args:
        data: Dict with competitor info, moat assessment, market position.

    Returns:
        HTML-formatted narrative string.
    """
    user_prompt = f"""
Write a 2-3 paragraph competitive landscape narrative for an Investment Due Diligence Memorandum.

COMPANY: {data.get('company_name', 'N/A')} ({data.get('ticker', 'N/A')})

COMPETITORS: {data.get('competitors_text', 'N/A')}
MOAT WIDTH: {data.get('moat_width', 'N/A')}
MOAT NARRATIVE: {data.get('moat_narrative', 'N/A')}
COMPETITIVE POSITION VERDICT: {data.get('competitive_verdict', 'N/A')}
KEY ADVANTAGES: {data.get('key_advantages', 'N/A')}
KEY VULNERABILITIES: {data.get('key_vulnerabilities', 'N/A')}
VALUATION VS PEERS: {data.get('valuation_context', 'N/A')}

Wrap each paragraph in <p> tags.
"""
    return _call_llm(SYSTEM_PROMPT_BASE, user_prompt)


def generate_risk_dimension_narrative(dimension_name: str, data: dict) -> str:
    """Generate a narrative paragraph for a specific risk dimension.

    Args:
        dimension_name: Name of the risk dimension (Financial, Market, etc.).
        data: Dict with dimension score, level, evidence items.

    Returns:
        HTML-formatted narrative paragraph.
    """
    user_prompt = f"""
Write 1-2 paragraphs analyzing the {dimension_name} risk dimension for an Investment Due Diligence Memorandum.

COMPANY: {data.get('company_name', 'N/A')}
DIMENSION: {dimension_name}
SCORE: {data.get('score', 'N/A')}/100
RISK LEVEL: {data.get('level', 'N/A')}
WEIGHT: {data.get('weight', 'N/A')}

EVIDENCE FINDINGS:
{data.get('evidence_text', 'No evidence available.')}

Write a professional assessment of this risk dimension. What are the key findings?
What should an investor pay attention to? Be specific and reference the evidence provided.

Wrap in <p> tags.
"""
    return _call_llm(SYSTEM_PROMPT_BASE, user_prompt, temperature=0.2)
